### ISSUE TITLE
Doesn't work anymore?

### ISSUE THREAD

**Issue by dmigous** [bomba5/TransferBot#2]
Seems bot dead :(

**Comment by bomba5** [comment]
I've started the service for you :) try it!
I don't keep it running anymore.

**Comment by dmigous** [comment]
@bomba5 thanks a lot! I use quite often. 

If you plan to stop it anyway maybe you could give some tips how to deploy my own version?

**Comment by bomba5** [comment]
Just refer to the [README](https://github.com/bomba5/TransferBot/blob/master/README.md) file, it contains all the info needed to deploy your own instance.
